year: 1500
balance_top_rows: 10
start_page: 1
start_capital:
  wars: 100.0
  lights: 0.0
rows:
  1: 6
  2: 6
  3: 6
  4: 6
  5: 6
mysql:
  url: jdbc:mysql://localhost:3306/northlights?useSSL=false&autoReconnect=true
  wars_table: wars1
  lights_table: lights
  user: root
  password: root